receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
    timeout: 1s

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true

extensions:
  health_check:
  pprof:          #Performance profiling

service:
  extensions: [ pprof, health_check ]
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ otlp/jaeger ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp/prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ loki ]